#ifndef __RIPPLESOUNDINGAME_CSID_H_
#define __RIPPLESOUNDINGAME_CSID_H_

enum {
	BGM_GAMEPLAYINGRIPLLE = 0,
	BGM_TITLE,
	SE_CANCEL,
	SE_DECIDE,
	SE_FROG,
	SE_FROGJUMP2,
	SE_LOG,
	SE_LOTASLEAF2,
	SE_PIRANHA,
	SE_RIPPLE_MIN,
	SE_VOLTEX_MAX,
	SE_VOLTEX_MID,
	SE_VOLTEX_MIN
};

#endif